<script type="text/javascript" src="{{ asset('portal/javascript/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/bootstrap.bundle.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/jquery.cookie.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/swiper-bundle.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/owl.carousel.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/wow.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/count-down.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/magnific-popup.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/map.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/map.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/jquery-waypoints.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/jquery-countTo.js') }}"></script>
<script type="text/javascript" src="{{ asset('portal/javascript/main.js') }}"></script>
